services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
      cache_from:
        - type=local,src=/tmp/.buildx-cache
      cache_to:
        - type=local,dest=/tmp/.buildx-cache-new,mode=max

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
      cache_from:
        - type=local,src=/tmp/.buildx-cache
      cache_to:
        - type=local,dest=/tmp/.buildx-cache-new,mode=max